repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: cargo-check
    -   id: fmt
    -   id: clippy
        args: ["--fix", "--allow-dirty", "--allow-staged", "--", "-W", "unused-imports"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
    -   id: ruff
        args: ["--fix"]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
        language_version: python3

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        language_version: python3
        additional_dependencies:
        -   pbr
