[package]
name = "shogi"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
bitvec = "1.0.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "shogi_benchmark"
harness = false
