from enum import Enum

class Address:
    column: int
    row: int

    def __init__(self, column: int, row: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def to_int(self) -> int: ...

class ColorType(Enum):
    Black = 0
    White = 1
    ColorNumber = 2

    def __init__(self, value: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PieceType(Enum):
    King = 1
    Gold = 2
    Rook = 3
    Bichop = 4
    Silver = 5
    Knight = 6
    Lance = 7
    Pawn = 8
    Dragon = 9
    Horse = 10
    ProSilver = 11
    ProKnight = 12
    ProLance = 13
    ProPawn = 14

    def __init__(self, value: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Piece:
    owner: ColorType
    piece_type: PieceType

    def __init__(self, owner: ColorType, piece_type: PieceType) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...

class Move:
    def __init__(self, csa: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def is_drop(self) -> bool: ...
    def is_promote(self) -> bool: ...
    def get_from(self) -> Address: ...
    def get_to(self) -> Address: ...
    def get_piece(self) -> Piece: ...

class Hand:
    pieces: list[Piece]
    counts: list[int]

    def __init__(self, pieces: list[Piece], counts: list[int]) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def add_piece(self, color_type: ColorType, piece_type: PieceType) -> None: ...
    def add_pieces(
        self, color_type: ColorType, piece_type: PieceType, count: int
    ) -> None: ...
    def decrease_piece(self, color_type: ColorType, piece_type: PieceType) -> None: ...
    def get_player_pieces(self, color_type: ColorType) -> list[Piece]: ...

class Board:
    def __init__(self, sfen: str) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, value: object) -> bool: ...
    def __ne__(self, value: object) -> bool: ...
    def deploy(
        self, address: Address, piece_type: PieceType, color: ColorType
    ) -> None: ...
    def startpos(self) -> None: ...
    def get_piece(self, address: Address) -> Piece: ...
    def search_moves(self, color: ColorType) -> list[Move]: ...
    def execute_move(self, moves: Move) -> None: ...
    def is_finished(self) -> tuple[bool, ColorType]: ...

class Game:
    def __init__(
        self, board: Board, move_number: int, turn: ColorType, winner: ColorType
    ) -> None: ...
    def input_board(self, sfen: str) -> None: ...
    def input_hand(self, sfen: str) -> None: ...
    def input_move_number(self, sfen: str) -> None: ...
    def input_turn(self, sfen: str) -> None: ...
    def is_finished(self) -> tuple[bool, ColorType]: ...
    def execute_move(self, moves: Move) -> None: ...
    def random_play(self) -> Game: ...
